version: '3.7'

volumes:
  mqtt_persist:

services:
#  swagbadge:
#    build:
#
#  environment:
#    MQTT_BROKER: '101.181.46.180'
#    MQTT_PORT: '1883'
#    TWITTER_API_KEY: ${TWITTER_API_KEY}
#    TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
#    TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
#    TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
  beenhugged:
    build:
      context: beenhugged
    working_dir: /code
    command: hugdetector
    volumes:
      - ./beenhugged:/code
    environment:
      TEST: 1
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_KEY_SECRET: ${TWITTER_API_KEY_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET}
      MQTT_BROKER: ${HUGGED_BROKER}
      PUSHOVER_USER: ${PUSHOVER_USER}
      PUSHOVER_KEY: ${PUSHOVER_KEY}
      REDIS_HOST: ${REDIS_HOST}
#      MQTT_USER: ${MQTT_USER}
#      MQTT_PASS: ${MQTT_PASS}
      #TWITTER_HANDLE: ${twitter_handle}
      #TIMEZONE: Pacific/Auckland
#    links:
#      - "mosquitto"
#  heartbeat:
#    build:
#      context: heartbeat
#    working_dir: /code
#    command: python3 ./heartbeat.py
#    volumes:
#      - ./heartbeat:/code
#    environment:
#      mqtt_user: ${mqtt_user}
#      mqtt_pass: ${mqtt_pass}
#    links:
#      - "mosquitto"
#  mosquitto:
#    build:
#      context: mosquitto
#    command: /run-dev.sh
#    ports:
#      - "8883:8883"
#      - "1883:1883"
#    environment:
#      MQTT_USER: ${MQTT_USER}
#      MQTT_PASS: ${MQTT_PASS}
#    volumes:
#      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
#      - mqtt_persist:/opt/persist
#      - ./mosquitto/run-dev.sh:/run-dev.sh
#    #  - /opt/certs/fullchain.pem:/var/lib/mosquitto/fullchain.pem
#    #  - /opt/certs/privkey.pem:/var/lib/mosquitto/privkey.pem
